name: journal-me-dev-env

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    tty: true
    volumes:
      - ../..:/workspaces:rw,cached
    init: true
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
     - ../.postgres-data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
