/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthenticatedUserIndexImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedUserProfileImport } from './routes/_authenticated/user/profile'
import { Route as AuthenticatedUserWriteAboutTopicImport } from './routes/_authenticated/user/write-about/$topic'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUserIndexRoute = AuthenticatedUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUserProfileRoute = AuthenticatedUserProfileImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUserWriteAboutTopicRoute =
  AuthenticatedUserWriteAboutTopicImport.update({
    id: '/user/write-about/$topic',
    path: '/user/write-about/$topic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/user/profile': {
      id: '/_authenticated/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof AuthenticatedUserProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/user/write-about/$topic': {
      id: '/_authenticated/user/write-about/$topic'
      path: '/user/write-about/$topic'
      fullPath: '/user/write-about/$topic'
      preLoaderRoute: typeof AuthenticatedUserWriteAboutTopicImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedUserProfileRoute: typeof AuthenticatedUserProfileRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
  AuthenticatedUserWriteAboutTopicRoute: typeof AuthenticatedUserWriteAboutTopicRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUserProfileRoute: AuthenticatedUserProfileRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
  AuthenticatedUserWriteAboutTopicRoute: AuthenticatedUserWriteAboutTopicRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/user/profile': typeof AuthenticatedUserProfileRoute
  '/user': typeof AuthenticatedUserIndexRoute
  '/user/write-about/$topic': typeof AuthenticatedUserWriteAboutTopicRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/user/profile': typeof AuthenticatedUserProfileRoute
  '/user': typeof AuthenticatedUserIndexRoute
  '/user/write-about/$topic': typeof AuthenticatedUserWriteAboutTopicRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/user/profile': typeof AuthenticatedUserProfileRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
  '/_authenticated/user/write-about/$topic': typeof AuthenticatedUserWriteAboutTopicRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/login'
    | '/user/profile'
    | '/user'
    | '/user/write-about/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/login'
    | '/user/profile'
    | '/user'
    | '/user/write-about/$topic'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/_authenticated/user/profile'
    | '/_authenticated/user/'
    | '/_authenticated/user/write-about/$topic'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/user/profile",
        "/_authenticated/user/",
        "/_authenticated/user/write-about/$topic"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/_authenticated/user/profile": {
      "filePath": "_authenticated/user/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user/": {
      "filePath": "_authenticated/user/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user/write-about/$topic": {
      "filePath": "_authenticated/user/write-about/$topic.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
